### ISSUE TITLE
applySpec returns null value as an object

### ISSUE THREAD

**Issue by gaston-flores** [flybondi/ramda-land#22]
When using `null` as a value in the `applySpec` spec, it returns an empty object.
```js
applySpec({
  aNull: null,
  aValue: 'hello'
})({})
```
Expected result:
```js
{ aNull: null, aValue: 'hello' }
```
Actual result:
```js
{ aNull: {}, aValue: 'hello' }
```

I believe the issue is [this typeof](https://github.com/flybondi/ramda-land/blob/master/src/apply-spec.js#L39), since the `typeof` of `null` is `object`

**Comment by nfantone** [comment]
@gaston-flores Good catch 👍🏼. #23 should address this.
